#!/usr/bin/env python3
"""Convert asert_table.h (C++) into asert_table.py (Python).

Parses the 511 ``int64_t`` literals inside ``LOG2_COMPUTE_TABLE`` and emits a
Python module exposing them as ``LOG2_COMPUTE_TABLE: tuple[int, ...]``. The
math itself is owned by FACTOR's scripts/gen_compute_table.py — this script
only re-shapes the already-computed integers.

Re-run after pulling a new asert_table.h from FACTOR:
    python3 electrum/asert/gen_asert_table.py
"""
import os
import re


HERE = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.join(HERE, "asert_table.h")
OUTPUT_PATH = os.path.join(HERE, "asert_table.py")
EXPECTED_ENTRIES = 511


def load_table(header_path: str) -> list[int]:
    table: list[int] = []
    in_array = False
    with open(header_path, "r") as f:
        for line in f:
            if "LOG2_COMPUTE_TABLE" in line and "{" in line:
                in_array = True
                continue
            if not in_array:
                continue
            if "};" in line:
                break
            for m in re.finditer(r"(-?\d+)LL", line):
                table.append(int(m.group(1)))
    if len(table) != EXPECTED_ENTRIES:
        raise SystemExit(
            f"Expected {EXPECTED_ENTRIES} entries in {header_path}, "
            f"got {len(table)}"
        )
    return table


def emit_python(table: list[int]) -> str:
    lines = [
        '"""ASERT log2(compute) lookup table — generated from asert_table.h."""',
        "# Generated by gen_asert_table.py. Do not edit by hand.",
        "# Source of truth: electrum/asert/asert_table.h (verbatim from FACTOR).",
        "",
        "LOG2_COMPUTE_TABLE: tuple[int, ...] = (",
    ]
    for i, value in enumerate(table):
        nbits = 2 * (i + 1)
        lines.append(f"    {value:>20},  # nBits={nbits:>4d}")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    table = load_table(HEADER_PATH)
    output = emit_python(table)
    with open(OUTPUT_PATH, "w") as f:
        f.write(output)
    print(f"Wrote {OUTPUT_PATH} ({len(table)} entries)")


if __name__ == "__main__":
    main()
